eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    register-with-eureka: false

server:
  port: 8888  #服务端口号

spring:
  application:
    name: third-party-client #服务名称--调用的时候根据名称来调用该服务的方法