server:
  port: 8761 #服务注册中心端口号

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka01 #服务注册中心IP地址
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
#    registerWithEureka: false #是否注册本服务（默认true）
#    fetchRegistry: false #拉取服务（默认true）
    serviceUrl: #注册中心对外暴露地址
      defaultZone: http://localhost:8762/eureka/
    registry-fetch-interval-seconds: 1
  server:
    use-read-only-response-cache: false
    # 关闭自我保护，当检测不到心跳，直接剔除，无论网络/服务原因
    enable-self-preservation: false
    # 清理服务间隔60秒
    eviction-interval-timer-in-ms: 60000